### ISSUE TITLE
Project status, deprecation & replacement

### ISSUE THREAD

**Issue by adamalton** [GoogleCloudPlatform/snapshot-debugger#99]
It's unclear from the README what the status of this project is, and what the plan is to replace it after the end of the stated support period in August 2023.

The [google-cloud-debugger](https://github.com/GoogleCloudPlatform/cloud-debug-python) package doesn't yet support Python 3.10 (see [#33](https://github.com/GoogleCloudPlatform/cloud-debug-python/issues/33)), and it seems that it won't support Python 3.10 because it's being deprecated. The [deprecation notice](https://cloud.google.com/debugger/docs/deprecations) suggests that _this_ project should be used as a replacement.

But in the README of this project, there's a section titled [Preview Limitations](https://github.com/GoogleCloudPlatform/snapshot-debugger/blob/d99f0ba821a94203440ba6213378843e172ce214/README.md#preview-limitations), the content of which suggests that Python 3 support is still not ready. To add further confusion, the [Python](https://github.com/GoogleCloudPlatform/snapshot-debugger/blob/d99f0ba821a94203440ba6213378843e172ce214/README.md#python) section says to install `google-python-cloud-debugger`, which is the deprecated project which this one is meant to replace.

And then the [Support Period](https://github.com/GoogleCloudPlatform/snapshot-debugger/blob/d99f0ba821a94203440ba6213378843e172ce214/README.md#support-period) section of the README says that support for this package will end in August 2023, just 3 months after the deprecation of the package that it's meant to replace.

Moreover, with regard to Google Cloud Debugger, it's unclear whether it's the Python package which is being deprecated, or the entire feature on GCP. If it's the latter, then how does that affect this package?

Could someone who's in the know please explain what is going on?

**Comment by jasonborg** [comment]
Hi Adam,

The Google Cloud Debugger is officially deprecated and will be shut down on May 31, 2023. This means the Cloud Debugger API will be shut down and the Debug page will be removed from the Google Cloud Console.

The Snapshot Debugger is an open source alternative we are providing for users, which now has support built into the [Java](https://github.com/GoogleCloudPlatform/cloud-debug-java), [Python](https://github.com/GoogleCloudPlatform/cloud-debug-python) and [Node.js](https://github.com/googleapis/cloud-debug-nodejs) agents. To be more specific, the current agents support both the Snapshot Debugger and the Cloud Debugger, and will select between the two based on configuration. This is why in Python’s case the documentation says to install `google-python-cloud-debugger`, it supports both environments, however beginning May 31, 2023 it will only work in the Snapshot Debugger environment.

The Snapshot Debugger alternative is currently supported and will continue to be supported until Aug 31 2023, along with the associated agents. There are no further plans to replace it at that time, the repositories can be forked by users if they wish to maintain them going forward. Users are encouraged to begin using this new alternative now so that we may begin addressing any issues they may have.

As you noted, currently the Python agent does not support Python 3.10. This is something we are investigating, however it may not be feasible to address.

Regards,
Jason

**Comment by jasonborg** [comment]
Regarding Python 3.10, google-python-cloud-debugger 3.3 has now been released with Python 3.10 support.
